name: Release
on:
    push:
        branches:
            - main
jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - name: Use Node.js 20
              uses: actions/setup-node@v4
              with:
                  node-version: 20
            - name: Install Dependencies
              run: npm ci
              env:
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
            - name: Create Release Pull Request or Publish to npm
              uses: changesets/action@v1
              with:
                  publish: npm run release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
